### ISSUE TITLE
Autoscaling Experiment.

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/cloud#399]

**Comment by Yancey1989** [comment]
Deadline: Oct 27, 2017
Design doc: https://github.com/PaddlePaddle/cloud/blob/develop/doc/autoscale_experiment.md
TODO:
- Make sure all demos in the book is running on Cloud correctly.
  - [x] 01.fit a line, #401 -- @putcn 
  - [ ] 02.recognize_digits, #405 -- @gongweibao 
  - [ ] 03.image_classification, 
  - [ ] 04.word2vec, #402 
  - [ ] 05.recommender_system, #406 -- @putcn 
  - [ ] 06.understand_sentiment, #407 
  - [ ] 07.label_semantic_roles, #404 
  - [ ] 08.machine_translation, #403 
- [ ] Implement scripts to submit the job.
- [ ] Implement the program that collects time series data for plotting graph(CPU and GPU utils).

BLOCK BUGS:

**Comment by gongweibao** [comment]
https://github.com/PaddlePaddle/cloud/projects/1

**Comment by Yancey1989** [comment]
## Cluster Resouces
```bash
CPU: 2348(Core)
GPU: 0(GPU card)
```
### TestCase1
- Submit two **GENERAL** jobs, mnist0(40 trainers, 15 pservsers),mnist1(45 trainers, 25 pservsers)

```bash
Total time: 420(s)
Average running time: 220(s)
Average pending time: 85(s)
mnist0 running time: 205(s)
mnist1 running time: 235(s)
```

- Details
```bash
Times	Name	Status	CPU	GPU	PARALLELISM
0	mnist0	WAITING	5.60	0	0   // no job has been submited
0	mnist1	WAITING	5.60	0	0
5	mnist0	WAITING	5.60	0	0
5	mnist1	WAITING	5.60	0	0
10	mnist0	RUNNING	29.88	0	40  // mnist0 starts to run
10	mnist1	WAITING	29.88	0	0
15	mnist0	RUNNING	29.88	0	40
15	mnist1	PENDING	29.88	0	34  // mnist1 pending, no enough resource
20	mnist0	RUNNING	50.32	0	40
20	mnist1	PENDING	50.32	0	45
...
180	mnist0	RUNNING	36.52	0	40
180	mnist1	PENDING	36.52	0	45
185	mnist0	RUNNING	39.59	0	40
185	mnist1	RUNNING	39.59	0	45  // minist1 running
210	mnist0	RUNNING	38.05	0	40
210	mnist1	RUNNING	38.05	0	45
215	mnist0	FINISH	37.54	0	40  // mnist0 finished
215	mnist1	RUNNING	37.54	0	45
220	mnist0	FINISH	37.54	0	40
220	mnist1	RUNNING	37.54	0	45
...
415	mnist0	FINISH	15.06	0	40
415	mnist1	RUNNING	15.06	0	45
420	mnist0	FINISH	14.54	0	40
420	mnist1	FINISH	14.54	0	45  // mnist 1 finished

```

**Comment by helinwang** [comment]
Great!!!

Maybe we can change the "WAITING" in `0	mnist0	WAITING	5.60	0	0` to "NOT EXISTS" or "N/A"? To me waiting means more like pending, which we already have.

**Comment by Yancey1989** [comment]
@helinwang I push a PR. #447 to reproduce the experiment, I think I will fixed 1. and 2. of your comment abvoe.

**Comment by helinwang** [comment]
@Yancey1989 I tried the following, and get error log on fault tolerant mode, it seems that the `ETCD_IP` environment variable is not set in the fault tolerant mode.
```
$ ./control_case1.sh start 1 ON
$ kc logs -f mnist0-trainer-w98q9
label selector: paddle-job-master=mnist0, desired: 1
Starting training job:  /pfs/mulan/home/helinwang@baidu.com/jobs/mnist0, num_gradient_servers: 2, trainer_id:  1, version: 
I1027 22:58:52.600109    28 Util.cpp:166] commandline:  --num_gradient_servers=2 --ports_num_for_sparse=1 --use_gpu=0 --trainer_id=1 --trainer_count=10 --num_passes=1 --ports_num=1 --port=7164 
[INFO 2017-10-27 22:58:52,696 layers.py:2556] output for __conv_pool_0___conv: c = 20, h = 24, w = 24, size = 11520
[INFO 2017-10-27 22:58:52,697 layers.py:2684] output for __conv_pool_0___pool: c = 20, h = 12, w = 12, size = 2880
[INFO 2017-10-27 22:58:52,698 layers.py:2556] output for __conv_pool_1___conv: c = 50, h = 8, w = 8, size = 3200
[INFO 2017-10-27 22:58:52,699 layers.py:2684] output for __conv_pool_1___pool: c = 50, h = 4, w = 4, size = 800
I1027 22:58:52.706857    28 GradientMachine.cpp:94] Initing parameters..
I1027 22:58:52.708870    28 GradientMachine.cpp:101] Init parameters done.
t=2017-10-27T22:58:57+0000 lvl=eror msg="Init etcd connection failed" error="dial tcp: lookup None on 11.1.0.10:53: no such host" stack="[github.com/PaddlePaddle/Paddle/go/pserver/client/etcd_client.go:145 c/cclient.go:129 _obj/_cgo_gotypes.go:109]"
t=2017-10-27T22:59:07+0000 lvl=eror msg="Init etcd connection failed" error="dial tcp: lookup None on 11.1.0.10:53: no such host" stack="[github.com/PaddlePaddle/Paddle/go/pserver/client/etcd_client.go:145 c/cclient.go:129 _obj/_cgo_gotypes.go:109]"
```

**Comment by helinwang** [comment]
For documentation purpose in case anyone else run into the problem:

For none fault tolerant job (`./control_case1.sh start 1 OFF`), I have to comment out the below line to make it start training reliably:
```git
     elif sys.argv[1] == "train":
-        prepare_dataset()
+        #prepare_dataset()
         main()
```

And to make the trainer run longer, we need to do:
```
-        num_passes=1)
+        num_passes=100)
```

**Comment by Yancey1989** [comment]
Hi @helinwang , I have update the PR #447 , please follow code :)  The update as following:
- Fix train_ft.py, fetch record from master
- Support `PASSES` and `JOB_COUNT` args to support run the experiment multipl tims.
- Generating a experiment report after all passes are finihsed.

**Comment by Yancey1989** [comment]
Remaining problems:
1. Scale down does not work, https://github.com/PaddlePaddle/cloud/issues/450,
1. The result of the experiment is unstable because of the unstable HDFS mount.

**Comment by jacquesqiao** [comment]
maybe can add definition description about `AVG_RUNNINT_TIME`, `AVG_PENDING_TIME` and `JOB_RUNNING_TIME`.

**Comment by helinwang** [comment]
@Yancey1989 got this error after starting autoscaler, seems to be a RBAC related issue, do you have any idea?
> E1030 21:10:27.490697       1 reflector.go:201] github.com/PaddlePaddle/cloud/go/controller/controller.go:100 : Failed to list *api.TrainingJob: User "system:serviceaccount:helinwang-baidu-com:default" cannot list trainingjobs.paddlepaddle.org at the cluster scope. (get TrainingJobs.paddlepaddle.org)

controller.yaml:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: training-job-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: training-job-controller
    spec:
      containers:
      - name: training-job-controller
        image: helinwang/training-job-controller
        imagePullPolicy: Always
        command: ["/controller", "-logtostderr", "-log_level", "debug"]
```

**Comment by Yancey1989** [comment]
>  I sent a PR to improve scale down: #456 . But could not test it because I got this error after starting > autoscaler, seems to be a RBAC related issue, do you have any idea?

The controller needs a ClusterRoleBind to bind with the ClusterRole(admin)，in the internal CPU cluster, please submit to namespace with **paddlecloud**

**Comment by helinwang** [comment]
Here is one run for test case 1 today:

`PASSES=5 JOB_COUNT=1 FAULT_TOLERANT=ON ./control_case1.sh start`

```
PASS_NUM|AVG_RUNNINT_TIME|AVG_PENDING_TIME|JOB_RUNNING_TIME|CPU_UTILS
0|2360|5|2360|13.69
1|320|5|320|14.54
2|1630|0|1630|13.91
3|4570|0|4570|14.80
4|5870|0|5870|14.94
TOTALLY|2950|2|N/A|14.38
```

**Comment by typhoonzero** [comment]
有一些问题请教：

case1：开启autoscale的情况，平均job执行时间变长了，整体集群CPU利用率上升不明显，而且貌似也没有达到很高的利用率？是否是因为每个pod request的CPU比较多呢？

case2：没有开启autoscale的情况，最后两行，trainer也变得很少，是job执行完成了么？这时是否nginx有大量pending的pod？

**Comment by helinwang** [comment]
同请教：

case1：为何autoscaling=ON会有pending？

case2：为何autoscaling=ON的时候有450s，而OFF的时候只有212s？

还有case2因为总时间是固定的，考虑加一个total trainer running time（trainer数在时间上的积分，越高越好）？

**Comment by helinwang** [comment]
Some helpful commands:

get total cluster CPU capacity:
```bash
kubectl describe nodes|grep -A1 Capacity|grep cpu|awk '{a=a+$2} END {print a}'
```

**Comment by putcn** [comment]
我们对于case 1是不是可以也收集下time series的每个pod和总体cpu的利用率, 这样我们就可以生成如下的图:
![image](https://user-images.githubusercontent.com/2062926/32249777-70c84ea2-be47-11e7-9f7f-839849b90ee6.png)
上下俩chart分别对应打开auto scale和没开的情况. 横轴为时间, 纵轴为CPU利用率. 
除了红色的每条线都是一个pod的CPU利用曲线, 通过这个可以看出来每个pod的调度情况, 这样可以显示出打开auto scale的情况下pending的time都很少.
红色的曲线代表总体CPU的利用率. 对时间求下积分, 算出x轴和红色曲线的面积, 作为CPU utilization score. 分数越高说明CPU做功越多. 如果同样功情况下时间越短, 说明效率越高. 
不知道我说明白了没...

**Comment by typhoonzero** [comment]
@putcn 这个方法甚好，而且足够直观。但可能需要 @Yancey1989 也记录执行过程的详细数值。

**Comment by helinwang** [comment]
@typhoonzero @Yancey1989 我改了下程序，能够输出每秒的情况，一会push上来。

**Comment by Yancey1989** [comment]
Cool!! Thanks @helinwang @putcn

**Comment by Yancey1989** [comment]
Update this PR #452 

1. Do not need to run `python main.py print_info`, the time serise data will be generated at `./out/mnist-case[1|2]-pass[0-9].log` folder.
1. Package the dataset and recordio files in the Docker image `registry.baidu.com/paddlepaddle/paddlecloud-job:mnist`
1. Add two colume in the time serise data, `running trainers for each job` and `cpu utils for each job`, @putcn could you help to add these two colume on the figure?

**Comment by putcn** [comment]
sure, will do

**Comment by helinwang** [comment]
Update today on #453 

1. Change case 2 so that it will run around 10 min for each experiment, no matter how many jobs has been submitted. The experiment will stop after the Nginx is scaled back to 400.

1. Not longer `rm ./out` every time, test will have different output folder depend on the configuration.
    So now you can run multiple experiments in a loop:
    ```
    $ for i in `seq 1 2`; do echo pass $i; TAG=round_$i JOB_COUNT=5 ./run.sh start case2; done
    pass 1
    outputing output to folder: ./out/mnist-OFF-5-1-ON-400-case_case2-round_1
    ```

**Comment by helinwang** [comment]
Remaining problem:

1. The max CPU util is capped around 85%, it would be great if we can explain why this happens, to the readers.

**Comment by helinwang** [comment]
Graph:

Test case 2:
Autoscaling ON:
![auto_on_0](https://user-images.githubusercontent.com/1724178/32303768-e50ea032-bf27-11e7-82c6-5fa9dcf9552e.png)

Autoscaling OFF:
![auto_off_0](https://user-images.githubusercontent.com/1724178/32303774-ecc67084-bf27-11e7-8034-6e93652bc22d.png)

**Comment by typhoonzero** [comment]
Running case1 with 20 jobs, with trainer cpu:2, pserver cpu:2:

some trainer pods error with:
```
label selector: paddle-job-pserver=mnist5, desired: 10
label selector: paddle-job-master=mnist5, desired: 1
Starting training job:  /pfs/mulan/home/wuyi05@baidu.com/jobs/mnist5, num_gradient_servers: 5, version:
I1102 03:27:33.970584    30 Util.cpp:166] commandline:  --num_gradient_servers=5 --ports_num_for_sparse=1 --use_gpu=0 --trainer_count=1 --num_passes=1 --ports_num=1 --port=7164
[INFO 2017-11-02 03:27:35,513 layers.py:2556] output for __conv_pool_0___conv: c = 20, h = 24, w = 24, size = 11520
[INFO 2017-11-02 03:27:35,514 layers.py:2684] output for __conv_pool_0___pool: c = 20, h = 12, w = 12, size = 2880
[INFO 2017-11-02 03:27:35,514 layers.py:2556] output for __conv_pool_1___conv: c = 50, h = 8, w = 8, size = 3200
[INFO 2017-11-02 03:27:35,515 layers.py:2684] output for __conv_pool_1___pool: c = 50, h = 4, w = 4, size = 800
I1102 03:27:35.520740    30 GradientMachine.cpp:94] Initing parameters..
I1102 03:27:35.522634    30 GradientMachine.cpp:101] Init parameters done.
panic: context deadline exceeded

goroutine 17 [running, locked to thread]:
main.paddle_new_etcd_master_client(0x7fc7bbffb4d4, 0x5, 0x40, 0x1c400000008)
	/paddle/build/go/src/github.com/PaddlePaddle/Paddle/go/master/c/client.go:85 +0x132
main._cgoexpwrap_3d60921c95c9_paddle_new_etcd_master_client(0x7fc7bbffb4d4, 0x5, 0x40, 0xd8bb14b74dceb600)
	command-line-arguments/_obj/_cgo_gotypes.go:100 +0x41
Aborted
job returned 134...setting pod return message...
===============================
termination log wroted...
```

**Comment by Yancey1989** [comment]
Hi @helinwang 

> The max cluster CPU util is capped around 85%, it would be great if we can explain why this happens, to the readers.

I think the reason is the same as #465 , There is a calico Pod which request 250m CPU running on each Node, and the Trainer Pod request 5 CPU in the epxeriment, so always some CPU is idle.

> case 1 there are many pending jobs. Maybe we need to be more aggressive for scale down, now we only scale down when util reaches 100%, maybe we should scale down when reaching 90% or 95%.

I submit a PR to fix this problem, #467

**Comment by Yancey1989** [comment]
Update #453 
1. Run case1 for 10 mins for each experiment, the same as case2.
1. Upload the logs to the `./experiment/result` foler.
1. Update the contorller Docker image to `registry.baidu.com/paddlepaddle/controller:yx2`, build from #467

**Comment by helinwang** [comment]
Update:

"Print less log, fix unit test" for https://github.com/PaddlePaddle/cloud/pull/467

**Comment by helinwang** [comment]
Problems:

1. Not very related to the experiment, but `kubectl get events` sometimes shows:
```
2m         2m          1         mnist4-trainer-xlqk1    Pod                                         Warning   FailedMount        kubelet, yq01-jpaas-paddle01-wrk18.yq01.baidu.com    Unable to mount volumes for pod "mnist4-trainer-xlqk1_helinwang-baidu-com(e8f619c6-c024-11e7-aa74-6c92bf4727a8)": timeout expired waiting for volumes to attach/mount for pod "helinwang-baidu-com"/"mnist4-trainer-xlqk1". list of unattached/unmounted volumes=[public mulan default-token-hkc45]
```

**Comment by helinwang** [comment]
TODO:

1. Let's always use the latest #453 for the experiment, as it contains changes to experiment script, train_ft.py.
1. Let's make our experiment command line **exactly the same**:
    I have found that when PASSES=2, the experiment log for PASS1 and PASS2 differs. So let's always use PASSES=1.
    - case 1:
        `TAG=round_0 AUTO_SCALING=ON PASSES=1 JOB_COUNT=20 ./run.sh start case1`
        `TAG=round_1 AUTO_SCALING=ON PASSES=1 JOB_COUNT=20 ./run.sh start case1`
         ...
        `TAG=round_0 AUTO_SCALING=OFF PASSES=1 JOB_COUNT=20 ./run.sh start case1`
        `TAG=round_1 AUTO_SCALING=OFF PASSES=1 JOB_COUNT=20 ./run.sh start case1`
    - case 2:
        `TAG=round_0 AUTO_SCALING=ON PASSES=1 JOB_COUNT=5 ./run.sh start case2`
        `TAG=round_1 AUTO_SCALING=ON PASSES=1 JOB_COUNT=5 ./run.sh start case2`
         ...
        `TAG=round_0 AUTO_SCALING=OFF PASSES=1 JOB_COUNT=5 ./run.sh start case2`
        `TAG=round_1 AUTO_SCALING=OFF PASSES=1 JOB_COUNT=5 ./run.sh start case2`

**Comment by helinwang** [comment]
Latest Graphs:

![1](https://user-images.githubusercontent.com/1724178/32357063-8615fa6a-bff6-11e7-8194-8b5b02a908b8.png)
![2](https://user-images.githubusercontent.com/1724178/32357064-888e6110-bff6-11e7-9c05-02c4b2bdb0a4.png)
![3](https://user-images.githubusercontent.com/1724178/32357066-89bfc042-bff6-11e7-9b88-bcfec7c8b748.png)
![4](https://user-images.githubusercontent.com/1724178/32357067-8b4da64a-bff6-11e7-8a15-b9f14ef70336.png)

**Comment by Yancey1989** [comment]
Update #453 
1. Package `train_ft.py` in the Docker image, and modify the `run.sh` to use the new Image to run the job.
1. Push the time series data under the `log` folder.

**Comment by helinwang** [comment]
Update #453 

1. Plotter: support averaging inputs on *different* timestamps

**Comment by helinwang** [comment]
Problem:

Sometimes case 2 stuck at:
> waiting for collector exit, generated file  ./out/case2-mnist-ON-5-1-ON-400-round_3/mnist-case1-pass0.csv
waiting for collector exit, generated file  ./out/case2-mnist-ON-5-1-ON-400-round_3/mnist-case1-pass0.csv
waiting for collector exit, generated file  ./out/case2-mnist-ON-5-1-ON-400-round_3/mnist-case1-pass0.csv
waiting for collector exit, generated file  ./out/case2-mnist-ON-5-1-ON-400-round_3/mnist-case1-pass0.csv

**Comment by helinwang** [comment]
我们最后会在timestamp 550截断试验（之后会kill job，实验数据没有意义）。
avg pending time不被影响。
avg cpu util受影响，统计方式是如下命令行：
```
at out/case1-mnist-OFF-20-1-ON-400-round_*/mnist-case1-pass0.log|awk -F, '{if ($1<=550) {a=a+$2; b=b+1}} END {print a/b}'
```

**Comment by Yancey1989** [comment]
Push a PR: #470 

1. Fix a bug, the controller does rewrite the node resource when executing the DryRun.
1. Fix the long pending time in a track way, shrink the time interval of submitting jobs.
1. Remainding Pods after delete the job with a track way: ```kubectl delete pod `kubectl get pods | | grep -v Terminating | awk '{print $1}'` ``` 
1. Rerun the experiment,  update the log files: `out/case1-mnist-ON-20-1-ON-400-round_{0-9}`, `out/case1-mnist-OFF-20-1-ON-400-round_{0-3}`

**Comment by helinwang** [comment]
Seems something wrong with the state of autoscaler, I have to kill the pod between every run of case 1 to see the expected experiment result.
```
for i in `seq 2 9`; do TAG=round_$i AUTO_SCALING=ON PASSES=1 JOB_COUNT=20 ./run.sh start case1; kc delete po `kc get pod --namespace paddlecloud|grep training |awk  '{print $1}'` --namespace paddlecloud; sleep 10; done
```

**Comment by typhoonzero** [comment]
> Seems something wrong with the state of autoscaler, I have to kill the pod between every run of case 1 to see the expected experiment result.

@Yancey1989 is that a bug of case 1 job submit scripts, it's not deleting jobs after they finishes?

**Comment by Yancey1989** [comment]
@typhoonzero , Yes, I fixed it by a tracking way, but I think it's a bug of controller or cloud server..
